name: terrain
description: Describes 3D terrains via height-map and array of patches and build renderable meshes.
version: 0.1.0
repository: https://github.com/xclud/dart_terrain

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  vector_math: ^2.1.4

dev_dependencies:
  lints: ^2.0.0
  test: ^1.22.0
